//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvivatecParty.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvivatecParty.Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do participante precisa ser fornecido.
        /// </summary>
        internal static string MSG_PARTICIPANTE_EMAIL_NULL {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_EMAIL_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do participante precisa ser válido.
        /// </summary>
        internal static string MSG_PARTICIPANTE_EMAIL_VALIDO {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_EMAIL_VALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login do participante deve possuir de 2 à 15 characters.
        /// </summary>
        internal static string MSG_PARTICIPANTE_LOGIN_MIN_MAX {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_LOGIN_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login do participante precisa ser fornecido.
        /// </summary>
        internal static string MSG_PARTICIPANTE_LOGIN_NULL {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_LOGIN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data e hora informada precisa ser maior ou igual a data de hoje.
        /// </summary>
        internal static string MSG_PARTICIPANTE_MELHORDIAHORA_VALIDO {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_MELHORDIAHORA_VALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do participante deve possuir de 2 à 50 characters.
        /// </summary>
        internal static string MSG_PARTICIPANTE_NOME_MIN_MAX {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_NOME_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do participante precisa ser fornecido.
        /// </summary>
        internal static string MSG_PARTICIPANTE_NOME_NULL {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_NOME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do participante deve possuir de 5 à 20 characters.
        /// </summary>
        internal static string MSG_PARTICIPANTE_SENHA_MIN_MAX {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_SENHA_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do participante precisa ser fornacida.
        /// </summary>
        internal static string MSG_PARTICIPANTE_SENHA_NULL {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_SENHA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve estar de acordo com as normas de segurança.
        /// </summary>
        internal static string MSG_PARTICIPANTE_SENHA_VALIDO {
            get {
                return ResourceManager.GetString("MSG_PARTICIPANTE_SENHA_VALIDO", resourceCulture);
            }
        }
    }
}
